### ISSUE TITLE
Artwork change frequency

### ISSUE THREAD

**Issue by sojusnik** [schomery/artworks#1]
Hey!

Would be great, if you could implement an option to adjust the artwork change frequency to one's needs, especially "on every new tab", "every x hours" or "every day".

Many thanks for this great add-on!

**Comment by E-VANCE** [comment]
+1

I used Chrome before and wanted to see a new artwork "on every new tab" – would very much appreciate if you could enhance the add-on...!

**Comment by E-VANCE** [comment]
Thanks for the recent update!! Great work 👍 Setting the hour frequency to "0" enables a new artwork in every tab, very smooth...!
